#!/usr/bin/env python
# encoding: utf-8
'''
autoencode.__init__ -- Automatically encode files using handbrake

autoencode.__init__ is a automatic Handbrake encoder with the option to watch a folder, copy files to a temp folder, encode, and move to a destination folder.

It defines autoencode

@author:     McSwindler

@copyright:  2015 James Swindle. All rights reserved.

@license:    MIT

@contact:    wilingua@gmail.com
@deffield    updated: 2015-05-02
'''

import sys
import os
import time
import string
import argparse
import traceback

from argparse import ArgumentParser
from os.path import expanduser
from autoencode import AutoEncode

__all__ = []
__version__ = 0.1
__date__ = '2015-05-02'
__updated__ = '2015-05-02'

DEBUG = 1
TESTRUN = 0
PROFILE = 0

def main(argv=None):
    '''Command line options.'''

    program_name = os.path.basename(sys.argv[0])
    program_version = "v0.1"
    program_build_date = "%s" % __updated__

    program_version_string = '%%prog %s (%s)' % (program_version, program_build_date)
    #program_usage = '''usage: spam two eggs''' # optional - will be autogenerated by optparse
    program_longdesc = '''''' # optional - give further explanation about what the program does
    program_license = "Copyright 2015 McSwindler (James Swindle)                                            \
                Licensed under the MIT License\nhttp://opensource.org/licenses/MIT"

    if argv is None:
        argv = sys.argv[1:]
    try:
        # setup option parser
        parser = ArgumentParser(version=program_version_string, epilog=program_longdesc, 
                                description=program_license, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
        parser.add_argument("-i", "--in", dest="indir", help="set input directory", nargs='+', metavar="PATH")
        parser.add_argument("-o", "--out", dest="outdir", help="set output directory", metavar="PATH")
        parser.add_argument("-t", "--temp", dest="tempdir", help="set temporary directory", metavar="PATH")
        parser.add_argument("-H", "--handbrake", dest="handbrake", help="path to handbrake executable", metavar="FILE")
        parser.add_argument("-O", "--options", dest="options", help="handbrake cli options to use", metavar="STRING")

        # set defaults
        parser.set_defaults(outdir=expanduser("~") + os.sep + "videos" + os.sep + "encoded", 
                            indir=expanduser("~") + os.sep + "videos",
                            handbrake="C:\Program Files\Handbrake\HandBrakeCLI.exe")

        # process options
        args = parser.parse_args(argv)

        if args.indir:
            print("indir = %s" % args.indir)
        if args.outdir:
            print("outdir = %s" % args.outdir)
        if args.tempdir:
            print("tempdir = %s" % args.tempdir)
        if args.options:
            args.options = string.split(args.options, ' ')

        # MAIN BODY #
        while True:
            AutoEncode(args)
            time.sleep(900) #15 minutes

    except Exception, e:
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help\n")
        print Exception, e
        print traceback.format_exc()
        return 2


if __name__ == "__main__":
    if TESTRUN:
        import doctest
        doctest.testmod()
    if PROFILE:
        import cProfile
        import pstats
        profile_filename = 'autoencode.__init___profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(0)
    sys.exit(main())